theme: jekyll-theme-tactile
title: leapmanlab.github.io
description: The GitHub home for the Laboratory of Cellular Imaging and Macromolecular Biophysics (https://www.nibib.nih.gov/labs-at-nibib/laboratory-cellular-imaging-and-macromolecular-biophysics-lcimb)
# remote_theme: daattali/beautiful-jekyll